version: '3.8'

services:
  db:
    image: mysql:8.1
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dds
      MYSQL_ROOT_PASSWORD: hola@1234
    volumes:
      - ./mysql:/var/lib/mysql